<?php
/**
 * SofortSetup
 *
 * PHP version 5
 *
 * @category Class
 * @package  FirstData\FirstApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Payment Gateway API Specification.
 *
 * The documentation here is designed to provide all of the technical guidance required to consume and integrate with our APIs for payment processing. To learn more about our APIs please visit https://docs.firstdata.com/org/gateway.
 *
 * The version of the OpenAPI document: 21.1.0.20210122.001
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.1.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace FirstData\FirstApi\Client\Model;

use \ArrayAccess;
use \FirstData\FirstApi\Client\ObjectSerializer;

/**
 * SofortSetup Class Doc Comment
 *
 * @category Class
 * @description Sofort setup.
 * @package  FirstData\FirstApi\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class SofortSetup implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'SofortSetup';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'customerId' => 'string',
        'projectId' => 'string',
        'apiKey' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'customerId' => null,
        'projectId' => 'string',
        'apiKey' => 'string'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'customerId' => 'customerId',
        'projectId' => 'projectId',
        'apiKey' => 'apiKey'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'customerId' => 'setCustomerId',
        'projectId' => 'setProjectId',
        'apiKey' => 'setApiKey'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'customerId' => 'getCustomerId',
        'projectId' => 'getProjectId',
        'apiKey' => 'getApiKey'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['customerId'] = isset($data['customerId']) ? $data['customerId'] : null;
        $this->container['projectId'] = isset($data['projectId']) ? $data['projectId'] : null;
        $this->container['apiKey'] = isset($data['apiKey']) ? $data['apiKey'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['customerId'] === null) {
            $invalidProperties[] = "'customerId' can't be null";
        }
        if ((mb_strlen($this->container['customerId']) > 10)) {
            $invalidProperties[] = "invalid value for 'customerId', the character length must be smaller than or equal to 10.";
        }

        if (!preg_match("/^[0-9]+$/", $this->container['customerId'])) {
            $invalidProperties[] = "invalid value for 'customerId', must be conform to the pattern /^[0-9]+$/.";
        }

        if ($this->container['projectId'] === null) {
            $invalidProperties[] = "'projectId' can't be null";
        }
        if ((mb_strlen($this->container['projectId']) > 10)) {
            $invalidProperties[] = "invalid value for 'projectId', the character length must be smaller than or equal to 10.";
        }

        if (!preg_match("/^[0-9]+$/", $this->container['projectId'])) {
            $invalidProperties[] = "invalid value for 'projectId', must be conform to the pattern /^[0-9]+$/.";
        }

        if ($this->container['apiKey'] === null) {
            $invalidProperties[] = "'apiKey' can't be null";
        }
        if ((mb_strlen($this->container['apiKey']) > 40)) {
            $invalidProperties[] = "invalid value for 'apiKey', the character length must be smaller than or equal to 40.";
        }

        if (!preg_match("/^[a-z0-9]+$/", $this->container['apiKey'])) {
            $invalidProperties[] = "invalid value for 'apiKey', must be conform to the pattern /^[a-z0-9]+$/.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets customerId
     *
     * @return string
     */
    public function getCustomerId()
    {
        return $this->container['customerId'];
    }

    /**
     * Sets customerId
     *
     * @param string $customerId Sofort customer identifier.
     *
     * @return $this
     */
    public function setCustomerId($customerId)
    {
        if ((mb_strlen($customerId) > 10)) {
            throw new \InvalidArgumentException('invalid length for $customerId when calling SofortSetup., must be smaller than or equal to 10.');
        }
        if ((!preg_match("/^[0-9]+$/", $customerId))) {
            throw new \InvalidArgumentException("invalid value for $customerId when calling SofortSetup., must conform to the pattern /^[0-9]+$/.");
        }

        $this->container['customerId'] = $customerId;

        return $this;
    }

    /**
     * Gets projectId
     *
     * @return string
     */
    public function getProjectId()
    {
        return $this->container['projectId'];
    }

    /**
     * Sets projectId
     *
     * @param string $projectId Sofort project identifier.
     *
     * @return $this
     */
    public function setProjectId($projectId)
    {
        if ((mb_strlen($projectId) > 10)) {
            throw new \InvalidArgumentException('invalid length for $projectId when calling SofortSetup., must be smaller than or equal to 10.');
        }
        if ((!preg_match("/^[0-9]+$/", $projectId))) {
            throw new \InvalidArgumentException("invalid value for $projectId when calling SofortSetup., must conform to the pattern /^[0-9]+$/.");
        }

        $this->container['projectId'] = $projectId;

        return $this;
    }

    /**
     * Gets apiKey
     *
     * @return string
     */
    public function getApiKey()
    {
        return $this->container['apiKey'];
    }

    /**
     * Sets apiKey
     *
     * @param string $apiKey API key provided by Sofort.
     *
     * @return $this
     */
    public function setApiKey($apiKey)
    {
        if ((mb_strlen($apiKey) > 40)) {
            throw new \InvalidArgumentException('invalid length for $apiKey when calling SofortSetup., must be smaller than or equal to 40.');
        }
        if ((!preg_match("/^[a-z0-9]+$/", $apiKey))) {
            throw new \InvalidArgumentException("invalid value for $apiKey when calling SofortSetup., must conform to the pattern /^[a-z0-9]+$/.");
        }

        $this->container['apiKey'] = $apiKey;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


